---
- message: You are using a deprecated behavior, it will be removed in version 1.23,
    Taxonomy.organizations_enabled is always true, settings to disable taxonomies
    has been removed in 1.21.
